[package]
name = "backend"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/blu3beri/vodo/packages/backend"
readme = "../../README.md"
keywords = ["todo"]
description = "backend for vodo"
license = "MIT"
categories = ["tui"]

[dependencies]
serde_json = "1.0.81"
chrono = "0.4"

[dependencies.serde]
version = "1.0.137"
features = ["derive"]
