[package]
name = "cli"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/blu3beri/vodo/packages/cli"
readme = "../../README.md"
keywords = ["cli"]
categories = ["cli"]
description = "cli interface for vodo"
license = "MIT"

[dependencies]
backend = { path = "../backend" }
